server:
  port: 8080
  servlet-path: /*
  context-path: /jpa
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3380/jpa?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: springboot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true